[project]
name = "gpt-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "langchain>=1.0.4",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.0.2",
]
